apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gzm8115nt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gzm8115nt-python 
  name: gzm8115nt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gzm8115nt-python 
